version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=200627
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=200627
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
